---
- name: Copy oracle sql script to host and update Oracle Password
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  
  tasks:
  - name: Copy Oracle SQL Scripts to Hosts
    copy:
      src: roles/files/changepwd.sql
      dest: /tmp/scripts/changepwd.sql
      owner: oracle
      group: oinstall
      mode: 0755
