---
- name: Copy oracle sql script to host and update Oracle Password
  hosts: all
  
  tasks:
  - name: Copy Oracle SQL Scripts to Hosts
    git:
      repo: https:/github.com/toburke1/oracle_password/scripts
      dest: /tmp/scripts
