---
- name: Copy oracle sql script to host and update Oracle Password
  hosts: all
  gather_facts: no
  
  tasks:
  - name: Copy Oracle SQL Scripts to Hosts
    copy:
      src: /home/oracle/software/changepwd.sql
      dest: /tmp/scripts/changepwd.sql
      owner: oracle
      group: oinstall
      mode: 0755
